"""create orders and payments

Revision ID: 5924511f8592
Revises:
Create Date: 2026-03-06 13:55:06.924851

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5924511f8592'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'orders',
        sa.Column(
            'total_amount', sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            'paid_amount', sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            'payment_status',
            sa.Enum(
                'UNPAID', 'PARTIALLY_PAID', 'PAID', name='order_payment_status'
            ),
            server_default='UNPAID',
            nullable=False,
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'payments',
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            'type',
            sa.Enum('CASH', 'ACQUIRING', name='payment_type'),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum(
                'CREATED',
                'PENDING',
                'PAID',
                'REFUNDED',
                'FAILED',
                name='payment_status',
            ),
            server_default='CREATED',
            nullable=False,
        ),
        sa.Column('bank_payment_id', sa.String(length=128), nullable=True),
        sa.Column('bank_status', sa.String(length=64), nullable=True),
        sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint('amount > 0', name='ck_payments_amount_gt_zero'),
        sa.ForeignKeyConstraint(
            ['order_id'],
            ['orders.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('bank_payment_id'),
    )
    op.create_index(
        op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('orders')
    # ### end Alembic commands ###
