"""empty message

Revision ID: 8941854978bb
Revises: a6165781740d
Create Date: 2026-03-09 15:38:04.669583

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '8941854978bb'
down_revision: Union[str, Sequence[str], None] = 'a6165781740d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
