"""empty message

Revision ID: a6165781740d
Revises: 5924511f8592
Create Date: 2026-03-06 17:17:31.753922

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a6165781740d'
down_revision: Union[str, Sequence[str], None] = '5924511f8592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'payments',
        sa.Column(
            'payment_type',
            sa.Enum('CASH', 'ACQUIRING', name='payment_type'),
            nullable=False,
        ),
    )
    op.drop_column('payments', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'payments',
        sa.Column(
            'type',
            postgresql.ENUM('CASH', 'ACQUIRING', name='payment_type'),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column('payments', 'payment_type')
    # ### end Alembic commands ###
