"""empty message

Revision ID: d8d4c5952cd6
Revises: de556c2a36d4
Create Date: 2026-03-11 14:47:14.763792

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'd8d4c5952cd6'
down_revision: Union[str, Sequence[str], None] = 'de556c2a36d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
