"""empty message

Revision ID: de556c2a36d4
Revises: 8941854978bb
Create Date: 2026-03-10 14:12:24.702497

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'de556c2a36d4'
down_revision: Union[str, Sequence[str], None] = '8941854978bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
